spring.datasource.url=jdbc:mysql://localhost:3306/event_ticket_db?serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=@Huut702812

# Hibernate configuration (Chỉ validate vì database đã tạo tay)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=8080

# JWT Configuration (Secret tối thiểu 32 ký tự, thời hạn 24 giờ)
app.jwt.secret=event_ticket_qr_checkin_secret_key_must_be_very_long_32_chars!
app.jwt.expiration-ms=86400000


# Phase 6 Configuration
app.upload.dir=./uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
